@host=http://localhost:5136

POST {{host}}/api/Authentication/Register
Content-Type: application/json

{
    "FirstName": "userId",
    "LastName": "userFirstName",
    "Email": "userLastName@gmail.com",
    "Password": "userLastName"
}

###

POST {{host}}/api/Authentication/Login
Content-Type: application/json

{
    "Email": "userLastName@gmail.com",
    "Password": "userLastName"
}

###

eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYTU2MmI2NC1hYTA2LTQ5MGItOTUxOS05MDg0MzRmOWEyNzQiLCJnaXZlbl9uYW1lIjoidXNlcklkIiwiZmFtaWx5X25hbWUiOiJ1c2VyRmlyc3ROYW1lIiwianRpIjoiNTkzMmM0MjktNDk3Mi00ZTJmLWI2ZDUtNWVhOTgxZDU1ZWExIiwidHdvRmFjdG9yRW5hYmxlZCI6InRydWUiLCJuYmYiOjE2NTg1NDIwMjEsImV4cCI6MTY1ODU0NTYyMSwiaXNzIjoiaHR0cDovL3d3d3cuZGVsbC5jb20vaWRlbnRpdHkiLCJhdWQiOiJ3d3cuZGVsbC5jb20ifQ.V5kbo0l8wfO9jSKw2u3O2e58Zb0AVaVHtyI5B-EFIGTctw62VTxbieM0Tz-_7tkt7CZ4AVrw58s1uD_f8A4MARAfy3dyd-z-OAHFCD4mF83948_dhS-RSNAyp1-jX8GUh7w2qUVKwFXZYnZsiCqMOF2NUptQ5thwwSQB5CtioVifq0-n7Ez2hXScPm-MVN18cecTi20Zlc-U2HILKnc-j-t0yKO-51ybbyGbSg8saxriawnn1mo-q8unS1WF2ANcVfzLdldKqFI-y8Em4MXPEWi-1qUlT6sMC8RGiqqhbQeDFRKtYrubRZf7zEsra9B3xXVJWnaL7MHvUoWbpOg1Ew
